[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--ignore-scripts"
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  NPM_CONFIG_BUILD_FROM_SOURCE = "false"
